package module

import (
	"strconv"

	"github.com/sagayosa/sayo_utils/utils"
)

const (
	RoleVoiceRecognize = "voice_recognize"
	RoleVoiceGenerate  = "voice_generate"
	RoleCore           = "core"
	RoleAI             = "ai"
	RoleDesktop        = "desktop"
	RolePlugin         = "plugin"
)

type HotKey struct {
	Key string `json:"key"`
	Url string `json:"url"`
}

type ModuleConfig struct {
	Identifier string `json:"identifier"`
	// Address    string `json:"address"`
	// Port       string `json:"port"`
	Role       string `json:"role"`
	EntryPoint string `json:"entry_point"`

	Name        string `json:"name"`
	Description string `json:"description"`
	Author      string `json:"author"`
	Preview     string `json:"preview"`

	HotKeys []*HotKey `json:"hotkeys"`
}

type ModuleInfo struct {
	ModuleConfig

	// if the module is registered through local configuration, address will be 127.0.0.1
	Address string `json:"address"`
	// if the module is registered through local configuration, port will be generated by framework
	Port       int    `json:"port"`
	ConfigPath string `json:"config_path"`
}

type Arg struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Declare struct {
	Root        string `json:"root"`
	Description string `json:"description"`
	URL         string `json:"url"`
	Args        []Arg  `json:"args"`
}

type PluginConfig struct {
	Declare []Declare `json:"declare"`
}

type Module struct {
	ModuleInfo
	PluginConfig
}

func (m *ModuleInfo) GetIdentifier() string {
	return m.Identifier
}

func (m *ModuleInfo) GetRole() string {
	return m.Role
}

func (m *ModuleInfo) GetIPInfo() string {
	return utils.StringPlus(m.Address, ":", strconv.Itoa(m.Port))
}

func (m *ModuleInfo) GetConfigPath() string {
	return m.ConfigPath
}
