package module

import (
	"strconv"

	"github.com/grteen/sayo_utils/utils"
)

const (
	RoleVoiceRecognize = "voice_recognize"
	RoleVoiceGenerate  = "voice_generate"
	RoleCore           = "core"
	RoleAI             = "ai"
	RoleDesktop        = "desktop"
	RolePlugin         = "plugin"
)

type ModuleConfig struct {
	Identifier string `json:"identifier"`
	// Address    string `json:"address"`
	// Port       string `json:"port"`
	Role       string `json:"role"`
	EntryPoint string `json:"entry_point"`

	Name        string `json:"name"`
	Description string `json:"description"`
	Author      string `json:"author"`
	Preview     string `json:"preview"`
}

type ModuleInfo struct {
	ModuleConfig

	// if the module is registered through local configuration, address will be 127.0.0.1
	Address string `json:"address"`
	// if the module is registered through local configuration, port will be generated by framework
	Port       int    `json:"port"`
	ConfigPath string `json:"config_path"`
}

type Module struct {
	ModuleInfo
}

func (m *ModuleInfo) GetIdentifier() string {
	return m.Identifier
}

func (m *ModuleInfo) GetRole() string {
	return m.Role
}

func (m *ModuleInfo) GetIPInfo() string {
	return utils.StringPlus(m.Address, ":", strconv.Itoa(m.Port))
}

func (m *ModuleInfo) GetConfigPath() string {
	return m.ConfigPath
}
