package sayoinnerhttp

type Module struct {
	ModuleInfo
}

type Plugin struct {
	ModuleInfo
	PluginConfig
}

type ModuleConfig struct {
	Identifier string `json:"identifier"`
	// Address    string `json:"address"`
	// Port       string `json:"port"`
	Role       string `json:"role"`
	EntryPoint string `json:"entry_point"`
}

type ModuleInfo struct {
	ModuleConfig

	// if the module is registered through local configuration, address will be 127.0.0.1
	Address string `json:"address"`
	// if the module is registered through local configuration, port will be generated by framework
	Port       int    `json:"port"`
	ConfigPath string `json:"config_path"`
}

type Arg struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Declare struct {
	Root        string `json:"root"`
	Description string `json:"description"`
	Args        []Arg  `json:"args"`
}

type PluginConfig struct {
	Declare []Declare `json:"declare"`
}
